"""empty message

Revision ID: 1df347cd40f6
Revises: 
Create Date: 2023-09-20 16:16:08.720064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df347cd40f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raccoons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trashcans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('raccoon_id', sa.Integer(), nullable=True),
    sa.Column('trashcan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['raccoon_id'], ['raccoons.id'], name=op.f('fk_visits_raccoon_id_raccoons')),
    sa.ForeignKeyConstraint(['trashcan_id'], ['trashcans.id'], name=op.f('fk_visits_trashcan_id_trashcans')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_table('trashcans')
    op.drop_table('raccoons')
    # ### end Alembic commands ###
